### ISSUE TITLE
[question] is the gen_statem code auto generated from the json specification?

### ISSUE THREAD

**Issue by juanbono** [CityBaseInc/states_language#1]
### Environment
None
* Elixir version (elixir -v) 
1.9.1
* Operating system:
Linux
### Expected behavior
Looking at the README.md I don't understand if the presented code was generated from the json file or the user has to code it.

In any case, thank you for developing this library, looks very interesting.

**Comment by entone** [comment]
Yes, the gen_statem code is auto-generated from the JSON specification, it is up to the user to define the callback behaviours. You can see all the callbacks here, https://hexdocs.pm/states_language/StatesLanguage.html#callbacks

You define `use StatesLanguage, data: my_json_file.json` in your module and implement the callbacks you need. All callbacks are optional.

The code in the example is written by the user. The library builds up all the gen_statem `handle_event` callbacks and exposes the callbacks linked above. Using pattern matching it transitions to the different states based on the actions returned from the user defined callbacks.

Generally a `handle_resource` callback can return `{:ok, data, [{:next_event, :internal, :my_transition_event}]}` to transition to the next state, but it is very flexible.

**Comment by entone** [comment]
Hi, thank you for you question. I've updated the docs to be a bit more explicit about creating the necessary files.

**Comment by juanbono** [comment]
Thanks! I've tried the code and works great! 
I'll close the issue.
